"""description

Revision ID: 93b895b01fc1
Revises: 001
Create Date: 2026-02-28 22:07:40.529540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b895b01fc1'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('indicator_cache_time_idx'), table_name='indicator_cache')
    op.drop_index(op.f('idx_indicator_cache_lookup'), table_name='indicator_cache')
    op.create_index('idx_indicator_cache_lookup', 'indicator_cache', ['symbol_id', 'timeframe', 'indicator_name', 'time'], unique=False)
    op.drop_index(op.f('idx_ingestion_log_symbol'), table_name='ingestion_log')
    op.create_index('idx_ingestion_log_symbol', 'ingestion_log', ['symbol_id', 'timeframe', 'fetched_at'], unique=False)
    op.drop_index(op.f('ohlcv_time_idx'), table_name='ohlcv')
    op.drop_index(op.f('idx_ohlcv_symbol_tf_time'), table_name='ohlcv')
    op.create_index('idx_ohlcv_symbol_tf_time', 'ohlcv', ['symbol_id', 'timeframe', 'time'], unique=False)
    op.drop_index(op.f('idx_pattern_detections_detected'), table_name='pattern_detections')
    op.create_index('idx_pattern_detections_detected', 'pattern_detections', ['detected_at'], unique=False)
    op.drop_constraint(op.f('sa_ratings_symbol_id_snapshot_date_key'), 'sa_ratings', type_='unique')
    op.drop_index(op.f('idx_sa_ratings_momentum'), table_name='sa_ratings')
    op.create_index('idx_sa_ratings_momentum', 'sa_ratings', ['momentum_grade', 'snapshot_date'], unique=False)
    op.drop_index(op.f('idx_sa_ratings_symbol_date'), table_name='sa_ratings')
    op.create_index('idx_sa_ratings_symbol_date', 'sa_ratings', ['symbol_id', 'snapshot_date'], unique=False)
    op.drop_index(op.f('idx_scan_results_symbol'), table_name='scan_results')
    op.create_index('idx_scan_results_symbol', 'scan_results', ['symbol_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_scan_runs_status'), table_name='scan_runs', postgresql_where="(status = ANY (ARRAY['pending'::scan_run_status, 'running'::scan_run_status]))")
    op.drop_index(op.f('idx_scan_runs_profile'), table_name='scan_runs')
    op.create_index('idx_scan_runs_profile', 'scan_runs', ['profile_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_swing_points_lookup'), table_name='swing_points')
    op.create_index('idx_swing_points_lookup', 'swing_points', ['symbol_id', 'timeframe', 'time'], unique=False)
    op.drop_index(op.f('idx_symbols_active'), table_name='symbols', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_symbols_active'), 'symbols', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index('idx_swing_points_lookup', table_name='swing_points')
    op.create_index(op.f('idx_swing_points_lookup'), 'swing_points', ['symbol_id', 'timeframe', sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_scan_runs_profile', table_name='scan_runs')
    op.create_index(op.f('idx_scan_runs_profile'), 'scan_runs', ['profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_scan_runs_status'), 'scan_runs', ['status'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::scan_run_status, 'running'::scan_run_status]))")
    op.drop_index('idx_scan_results_symbol', table_name='scan_results')
    op.create_index(op.f('idx_scan_results_symbol'), 'scan_results', ['symbol_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_sa_ratings_symbol_date', table_name='sa_ratings')
    op.create_index(op.f('idx_sa_ratings_symbol_date'), 'sa_ratings', ['symbol_id', sa.literal_column('snapshot_date DESC')], unique=False)
    op.drop_index('idx_sa_ratings_momentum', table_name='sa_ratings')
    op.create_index(op.f('idx_sa_ratings_momentum'), 'sa_ratings', ['momentum_grade', sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_unique_constraint(op.f('sa_ratings_symbol_id_snapshot_date_key'), 'sa_ratings', ['symbol_id', 'snapshot_date'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_pattern_detections_detected', table_name='pattern_detections')
    op.create_index(op.f('idx_pattern_detections_detected'), 'pattern_detections', [sa.literal_column('detected_at DESC')], unique=False)
    op.drop_index('idx_ohlcv_symbol_tf_time', table_name='ohlcv')
    op.create_index(op.f('idx_ohlcv_symbol_tf_time'), 'ohlcv', ['symbol_id', 'timeframe', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('ohlcv_time_idx'), 'ohlcv', [sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_ingestion_log_symbol', table_name='ingestion_log')
    op.create_index(op.f('idx_ingestion_log_symbol'), 'ingestion_log', ['symbol_id', 'timeframe', sa.literal_column('fetched_at DESC')], unique=False)
    op.drop_index('idx_indicator_cache_lookup', table_name='indicator_cache')
    op.create_index(op.f('idx_indicator_cache_lookup'), 'indicator_cache', ['symbol_id', 'timeframe', 'indicator_name', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('indicator_cache_time_idx'), 'indicator_cache', [sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
